spring:
  profiles:
    active:
      - dev
---
server:
  port: 9501

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:a@eureka1:7001/eureka,http://admin:a@eureka2:7002/eureka,http://admin:a@eureka3:7003/eureka
    register-with-eureka: true     #暂时不注册
  instance:
    instance-id: piclibservice-zuul-gateway
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2    #设置心跳间隔时间
    lease-expiration-duration-in-seconds: 5  # 租约超时时间间隔

spring:
  profiles: dev
  application:
    name:  piclibservice-zuul-gateway
  security:
    user:
      name: admin
      password: a



