spring:
  profiles:
    active:
      - dev
---
server:
  port: 9501

spring:
  profiles: dev
  application:
    name:  piclibservice-zuul-gateway
  security:
    user:
      name: admin
      password: a
#公共前缀
zuul:
  routes:
    product:
      path: /pics-proxy/**
      serviceId: piclibservice-provider
      sensitiveHeaders:
  ignored-services:
    "*"
  prefix: /yc-api    #公共前缀


