spring:
  profiles:
    active:
      - dev
---
server:
  port: 9501

spring:
  profiles: dev
  application:
    name:  piclibservice-zuul-gateway
  security:
    user:
      name: admin
      password: a



